#!/usr/bin/env bash
# Install nginx web server 
sudo apt-get update -y
sudo apt-get install nginx -y
# Adjust the firewall
sudo ufw allow 'OpenSSH'
sudo ufw allow 'Nginx HTTP'
sudo cp /var/www/html/index.nginx-debian.html /var/www/html/bkup_index.nginx-debian.html
sudo su
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo service nginx start
