#!/usr/bin/env bash

# Install nginx and start it
sudo apt-get update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "Hello World!" >> /var/www/html/index.html
echo -e "Ceci n'est pas une page\n" | sudo tee /usr/share/nginx/html/custom_404.html
new_string="\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n"
error_str="\n\terror_page 404 /custom_404.html;\n\tlocation = /custom_404.html {\n\t\troot /usr/share/nginx/html;\n\t\tinternal;\n\t}\n"
sudo sed -i "37a\ $new_string" /etc/nginx/sites-enabled/default
sudo sed -i "37a\ $error_str" /etc/nginx/sites-enabled/default
sudo service nginx start
