#!/usr/bin/env bash
# Install and configure HAproxy on lb-01 server
sudo apt-get install -y software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-1.8
sudo apt-get update
sudo apt-get install -y haproxy
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.bak
conf="\nfrontend node-http\n\tbind *:80\n\tmode http\n\tdefault_backend web-backend\n\nbackend web-backend\n\tbalance roundrobin\n\toption forwardfor\n\tserver 66984-web-01 54.90.61.141:80 check\n\tserver 66984-web-02 54.84.14.53:80 check\n\n"
echo -e "$conf" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy start
