#!/usr/bin/env bash
# Nginx likes port 80
sudo sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default
sudo rm -f /etc/nginx/sites-enabled/default
sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
